import {players} from "./data.js";
const labels={tacklesPer90:"Tackles /90",pressuresPer90:"Pressures /90",foulsPer90:"Fouls /90",progressiveCarriesPer90:"Progressive carries /90",progressivePassesPer90:"Progressive passes /90",xAPer90:"xA /90",assistsPer90:"Assists /90",goalsPer90:"Goals /90",xGPer90:"xG /90",successfulDribblesPer90:"Successful dribbles /90"};
// Vocabulary layer: each vague football phrase maps to measurable minimums.
const rules=[{terms:["aggressive"],metrics:{tacklesPer90:2.2,pressuresPer90:16,foulsPer90:1.3}},{terms:["box-to-box","box to box"],metrics:{tacklesPer90:2,progressiveCarriesPer90:2.8,progressivePassesPer90:4.5}},{terms:["creative"],metrics:{xAPer90:.18,assistsPer90:.16,progressivePassesPer90:5}},{terms:["clinical"],metrics:{goalsPer90:.4,xGPer90:.38}},{terms:["good dribbler","dribbler"],metrics:{successfulDribblesPer90:2,progressiveCarriesPer90:3.5}}];
const state={filters:[]},$=s=>document.querySelector(s);
const filterDefinitions=[
 {key:"age",label:"Maximum age",op:"max",value:25,unit:"years"},{key:"marketValue",label:"Maximum value",op:"max",value:50,unit:"£m"},{key:"position",label:"Position",op:"equals",value:"Midfielder",unit:""},
 ...Object.entries(labels).map(([key,label])=>({key,label,op:"min",value:key.includes("pressures")?15:key.includes("Passes")?5:key.includes("Carries")?3:key.includes("tackles")?2:key.includes("Dribbles")?2:key.includes("fouls")?1.2:.2,unit:"min"})),
 {key:"interceptionsPer90",label:"Interceptions /90",op:"min",value:1,unit:"min"}
];
function renderFilterPicker(){const available=filterDefinitions.filter(def=>!state.filters.some(f=>f.key===def.key));$("#new-filter").innerHTML=available.length?available.map(def=>`<option value="${def.key}">${def.label}</option>`).join(""):`<option>All filters added</option>`;$("#add-filter").disabled=!available.length}
function parsePrompt(prompt){const text=prompt.toLowerCase(),filters=[];if(/young|youthful/.test(text))filters.push({key:"age",label:"Maximum age",op:"max",value:23,unit:"years"});const budget=text.match(/under\s*(?:£|gbp)?\s*(\d+)\s*m/i);if(budget)filters.push({key:"marketValue",label:"Maximum value",op:"max",value:+budget[1],unit:"£m"});const positions=[[/midfield/,"Midfielder"],[/forward|striker|winger/,"Forward"],[/defender|centre-back|full-back/,"Defender"]];const pos=positions.find(([r])=>r.test(text));if(pos)filters.push({key:"position",label:"Position",op:"equals",value:pos[1],unit:""});rules.forEach(rule=>{if(rule.terms.some(term=>text.includes(term)))Object.entries(rule.metrics).forEach(([key,value])=>{const found=filters.find(f=>f.key===key);if(found)found.value=Math.max(found.value,value);else filters.push({key,label:labels[key],op:"min",value,unit:"min"})})});return filters.length?filters:[{key:"age",label:"Maximum age",op:"max",value:26,unit:"years"}]}
function renderFilters(){$("#filter-list").innerHTML=state.filters.map((f,i)=>`<div class="filter-row"><div><label for="f-${i}">${f.label}</label><small>${f.op==="min"?"Minimum target":f.op==="max"?"Upper limit":"Required"}</small></div>${f.op==="equals"?`<select id="f-${i}" data-index="${i}">${["Midfielder","Forward","Defender"].map(p=>`<option ${p===f.value?"selected":""}>${p}</option>`).join("")}</select>`:`<div class="number-input"><input id="f-${i}" data-index="${i}" type="number" step="0.1" value="${f.value}"><span>${f.unit}</span></div>`}<button class="remove-filter" data-remove="${i}" aria-label="Remove ${f.label}">×</button></div>`).join("");renderFilterPicker()}
// Every active filter is equally weighted. Near misses get proportional partial
// credit, then the average is converted to a transparent 0–100 match percentage.
function scorePlayer(player){let total=0;const hits=[];state.filters.forEach(f=>{const actual=player[f.key];let score;if(f.op==="equals")score=actual===f.value?1:0;else if(f.op==="max")score=actual<=f.value?1:Math.max(0,1-(actual-f.value)/Math.max(f.value*.4,1));else score=Math.min(1,actual/f.value);total+=score;if(score>=.9)hits.push(f.key)});return{player,percentage:Math.round(total/Math.max(state.filters.length,1)*100),hits}}
function why(r){const p=r.player,h=r.hits,a=[];if(h.includes("age"))a.push(`only ${p.age}`);if(h.includes("marketValue"))a.push(`within budget at £${p.marketValue}m`);if(h.includes("tacklesPer90")||h.includes("pressuresPer90"))a.push("high defensive intensity");if(h.includes("progressiveCarriesPer90"))a.push("strong ball progression");if(h.includes("progressivePassesPer90"))a.push("progressive passer");if(h.includes("goalsPer90"))a.push("reliable goal output");if(h.includes("successfulDribblesPer90"))a.push("elite 1v1 threat");return a.slice(0,3).join(" · ")||`Closest available ${p.position.toLowerCase()} profile`}
function avatar(p){return p.name.split(" ").map(n=>n[0]).join("").slice(0,2)}
function renderResults(){const ranked=players.map(scorePlayer).sort((a,b)=>b.percentage-a.percentage);$("#result-count").textContent=ranked.length;$("#results-body").innerHTML=ranked.map((r,i)=>`<tr><td class="rank">${String(i+1).padStart(2,"0")}</td><td><div class="player"><span class="player-avatar">${avatar(r.player)}</span><div><strong>${r.player.name}</strong><small>${r.player.club} · ${r.player.country}</small></div></div></td><td><strong>${r.player.position}</strong><small>${r.player.age} years old</small></td><td><strong>£${r.player.marketValue}m</strong></td><td class="reason">${why(r)}</td><td><div class="score"><strong>${r.percentage}%</strong><span><i style="width:${r.percentage}%"></i></span></div></td></tr>`).join("");$("#mobile-results").innerHTML=ranked.map((r,i)=>`<article><div class="mobile-top"><span class="rank">${String(i+1).padStart(2,"0")}</span><div class="player"><span class="player-avatar">${avatar(r.player)}</span><div><strong>${r.player.name}</strong><small>${r.player.club} · ${r.player.age}</small></div></div><strong class="mobile-score">${r.percentage}%</strong></div><p>${why(r)}</p><div class="score"><span><i style="width:${r.percentage}%"></i></span></div></article>`).join("")}
function generate(scroll=false){state.filters=parsePrompt($("#prompt").value);renderFilters();renderResults();if(scroll)$("#workspace").scrollIntoView({behavior:"smooth",block:"start"})}
$("#prompt-form").addEventListener("submit",e=>{e.preventDefault();generate(true)});$("#filter-list").addEventListener("input",e=>{const f=state.filters[e.target.dataset.index];if(f)f.value=e.target.type==="number"?+e.target.value:e.target.value});$("#filter-list").addEventListener("click",e=>{if(e.target.dataset.remove!==undefined){state.filters.splice(+e.target.dataset.remove,1);renderFilters()}});$("#add-filter").addEventListener("click",()=>{const definition=filterDefinitions.find(def=>def.key===$("#new-filter").value);if(definition){state.filters.push({...definition});renderFilters()}});$("#search-players").addEventListener("click",renderResults);$("#reset-filters").addEventListener("click",()=>generate());document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>{$("#prompt").value=b.dataset.prompt;generate(true)}));$("#dataset-count").textContent=players.length;generate();
